### ISSUE TITLE
Random 404's - Can you resolve?

### ISSUE THREAD

**Issue by Matt2021-A** [skytap/well-architected-framework#146]
Just clicking around in the WAF - I'm getting 404's for:
https://skytap.github.io/well-architected-framework/security/security-as-a-service/
https://skytap.github.io/well-architected-framework/design-considerations-azure

**Comment by jm-carolinah** [comment]
The correct link for design considerations azure is
https://skytap.github.io/well-architected-framework/resiliency/design-considerations-azure
I couldn't find where's anchored that link, can you help me find it?

Just pushed changes to the 146-random-404s-can-you-resolve branch.
Turns out, we had to remove the slash at the end of those links, that's just the way github pages work, ugh.
Links in the sidebar are working now.
